Add RackAwareDistributionGoal hard goal
linkedin/cruise-control-ui pull request #51
Opened 2020-11-04 16:31 UTC by rhardouin

New hard goal RackAwareDistributionGoal is missing

2020-11-07 13:25 UTC, nareshv requested changes
Is there a minimum CC version thats required for this goal to work ? We can add this to the commit notes ?

2020-11-09 10:29 UTC, rhardouin commented
Hi @nareshv 

> Is there a minimum CC version thats required for this goal to work ? 
Yes it's been added in 2.0.131

>We can add this to the commit notes ?
I've changed the commit message and I'll also update the PR message

2020-11-11 04:51 UTC, nareshv commented
Please review https://github.com/linkedin/cruise-control-ui/blob/master/CONTRIBUTING.md and confirm you are ok with the guidelines ?

2020-11-11 09:19 UTC, rhardouin commented
Yes @nareshv, I'm OK with the guidelines :+1:

2020-11-11 12:02 UTC, merged